---
####################################################################
# Example :  Journal Volume Playbook
####################################################################
- name: Journal Volume Module
  hosts: localhost
  gather_facts: false

  vars_files:
    - ansible_vault_storage_var.yml

  vars:
    # Common connection info for all tasks
    connection_info:
      address: "{{ storage_address }}"
      username: "{{ vault_storage_username }}"
      password: "{{ vault_storage_secret }}"
  tasks:

    ####################################################################
    # Task 1 : Create ldev
    ####################################################################
    - name: Create ldev
      hitachivantara.vspone_block.vsp.hv_ldev:
        connection_info: "{{ connection_info }}"
        state: "present"
        spec:
          ldev_id: "{{ journal_ldev_id }}"
          pool_id: "{{ journal_pool_id }}"
          size: "{{ journal_size }}"
      register: result

    - name: Debug the result variable
      ansible.builtin.debug:
        var: result

    ####################################################################
    # Task 1 : Create a Journal Volume using required details
    ####################################################################
    - name: Create a Journal Volume using required details
      hitachivantara.vspone_block.vsp.hv_journal_volume:
        connection_info: "{{ connection_info }}"
        state: "present"
        spec:
          journal_id: "{{ onprem_journal_id }}"
          ldev_ids: ["{{ journal_ldev_id }}"]
      register: result

    - name: Debug the result variable
      ansible.builtin.debug:
        var: result
