####################################################################
# Create a volume in the cloud storage and attach it to a compute node.
####################################################################
- name: Volume Module
  hosts: localhost
  gather_facts: false
  no_log: false
  collections:
    - hitachivantara.vspone_block.sds_block
  vars_files:
    - ansible_vault_storage_var.yml

  vars:
    # Common connection info for all tasks
    connection_info:
      address: "{{ cloud_storage_address }}"
      username: "{{ cloud_vault_storage_username }}"
      password: "{{ cloud_vault_storage_secret}}"
  tasks:
    ####################################################################
    # Task 1 : Create volume
    ####################################################################
    - name: Create and attach volume
      hitachivantara.vspone_block.sds_block.hv_sds_block_volume:
        connection_info: "{{ connection_info }}"
        state: "present"
        spec:
          name: "{{ cloud_vol_name }}"
          capacity: "{{ cloud_vol_capacity }}"
          pool_name: "{{ cloud_pool_name }}"
          capacity_saving: "Disabled"
          compute_nodes: ["{{ cloud_compute_node_name }}"]
      register: result
    - name: Debug the result variable
      ansible.builtin.debug:
        var: result
    - name: Set Volume Number for workflow
      set_stats:
        data:
          cloud_svol_id: "{{ result.data.volume_number }}"
    - name: Set Storage Controller ID for workflow
      set_stats:
        data:
          storage_controller_id: "{{ result.data.storage_controller_id }}"
    