---
####################################################################
# Cloud HUR Journal Creation
####################################################################
- name: Create Cloud HUR Journal
  hosts: localhost
  vars_files:
    - ansible_vault_storage_var.yml
  tasks:
    - name: Check if Journal Volume exists
      ansible.builtin.shell: |
        set -o pipefail
        hsds --ignore_certificate_errors \
          --host "{{ az_cloud_storage_address }}" \
          --user "{{ az_cloud_vault_storage_username }}" \
          --password "{{ az_cloud_vault_storage_secret }}" \
          volume_show \
          --id_name "{{ cloud_journal_name }}"
      ignore_errors: true
      register: command_result

    - name: Create Journal Volume and get Job ID
      ansible.builtin.shell: |
        set -o pipefail
        hsds --ignore_certificate_errors \
          --host "{{ az_cloud_storage_address }}" \
          --user "{{ az_cloud_vault_storage_username }}" \
          --password "{{ az_cloud_vault_storage_secret }}" \
          volume_create \
          --base_name_for_name "{{ cloud_journal_name }}" \
          --storage_controller_id "{{ storage_controller_id }}" \
          --capacity 102400 \
          --pool_id_name "{{ cloud_pool_name }}" | \
          grep -i "^Job" | tr -d " " | cut -d":" -f2 | tr -d "\n"
      when: command_result.rc != 0
      register: job_id

    - ansible.builtin.set_fact:
        job_id_out: "{{ job_id.stdout.strip() }}"

    - name: Get Journal Volume ID
      ansible.builtin.shell: |
        set -o pipefail
        hsds --ignore_certificate_errors \
          --host "{{ az_cloud_storage_address }}" \
          --user "{{ az_cloud_vault_storage_username }}" \
          --password "{{ az_cloud_vault_storage_secret }}" \
          volume_show \
          --id_name "{{ cloud_journal_name }}" |\
          grep "^Id:" | tr -d " " | cut -d":" -f2 | tr -d "\n"
      register: volume_id
      until: volume_id.rc == 0
      retries: 10
      delay: 30
    - name: Echo volume_id
      ansible.builtin.debug:
        msg: "{{ volume_id.stdout.strip() }}"

    - ansible.builtin.set_fact:
        volume_id_out: "{{ volume_id.stdout.strip() }}"

    - name: Check if Journal already exists
      ansible.builtin.shell: |
        set -o pipefail
        hsds --ignore_certificate_errors \
          --host "{{ az_cloud_storage_address }}" \
          --user "{{ az_cloud_vault_storage_username }}" \
          --password "{{ az_cloud_vault_storage_secret }}" \
          journal_show \
          --journal_number "{{ cloud_journal_number }}"
      ignore_errors: true
      register: command_output

    - name: Create Journal
      ansible.builtin.shell: |
        set -o pipefail
        hsds --ignore_certificate_errors \
          --host "{{ az_cloud_storage_address }}" \
          --user "{{ az_cloud_vault_storage_username }}" \
          --password "{{ az_cloud_vault_storage_secret }}" \
          journal_create \
          --volume_ids "{{ volume_id_out }}" \
          --journal_number "{{ cloud_journal_number }}"
      when: command_output.rc !=0
      register: command_output

    - name: Echo command output
      ansible.builtin.debug:
        msg: "{{ command_output.stdout.strip() }}"
