---
- name: Create Azure Windows VM
  hosts: localhost
  connection: local
  gather_facts: no

  vars:
    resource_group: SQLServerAnalystRG
    location: westeurope
    vm_name: SQLServerAnalyst
    admin_username: azureuser
    admin_password: Hitachi1234!
    vm_size: Standard_DS1_v2
    image_publisher: MicrosoftWindowsServer
    image_offer: WindowsServer
    image_sku: 2019-Datacenter
    network_name: VSPOneNetwork
    subnet_name: ControlNetwork
    public_ip_name: SQLServerAnalystPublicIP
    nsg_name: CoESDS1180587-Control_nsg
    nic_name: SQLServerAnalystNIC
    azure_subscription_id: "2ffe3392-9c10-4024-b6e1-35addf3ca09b"
    azure_client_id: "a3bbfe70-bc44-4409-8e27-40f100103752"
    azure_secret: "FfG8Q~5kqUkvDuUH6VRvwIFdUWBVoHX1VUMHaaPI"
    azure_tenant: "18791e17-6159-4f52-a8d4-de814ca8284a"
 
  tasks:

    - name: Create Azure Resource Group
      azure_rm_resourcegroup:
        name: "{{ resource_group }}"
        location: westeurope
        subscription_id: "{{ azure_subscription_id }}"
        client_id: "{{ azure_client_id }}"
        secret: "{{ azure_secret }}"
        tenant: "{{ azure_tenant }}"

    - name: Create a public IP address
      azure_rm_publicipaddress:
        resource_group: "{{ resource_group }}"
        name: "{{ public_ip_name }}"
        allocation_method: Static

    - name: Create a network interface card (NIC)
      azure_rm_networkinterface:
        resource_group: "{{ resource_group }}"
        name: "{{ nic_name }}"
        virtual_network_name: "{{ network_name }}"
        subnet_name: "{{ subnet_name }}"
        public_ip_address_name: "{{ public_ip_name }}"
        network_security_group_name: "{{ nsg_name }}"

    - name: Create a Windows virtual machine
      azure_rm_virtualmachine:
        resource_group: "{{ resource_group }}"
        name: "{{ vm_name }}"
        vm_size: "{{ vm_size }}"
        admin_username: "{{ admin_username }}"
        admin_password: "{{ admin_password }}"
        image:
          publisher: "{{ image_publisher }}"
          offer: "{{ image_offer }}"
          sku: "{{ image_sku }}"
          version: latest
        os_disk_name: "{{ vm_name }}-osdisk"
        network_interfaces:
          - "{{ nic_name }}"
        tags:
          environment: production
          os: windows